version: '3.10'

services:
  kotlin-restful-api:
    container_name: kotlin-restful-api
    image: kotlin-restful-api:0.0.1
    ports:
      - 8080:8080
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      DATABASE_URL: jdbc:mysql://kotlin-restful-api-mysql:3306/restfulapi
    depends_on:
      - kotlin-restful-api-mysql

  kotlin-restful-api-mysql:
    container_name: kotlin-restful-api-mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: restfulapi

